services:
  backend:
    build: ./backend
    ports:
      - "4001:4001"
    privileged: true
    volumes:
      - ./backend:/app
      - ./backend/plugins/uploads:/app/uploads
      - ./backend/plugins/temp:/app/temp
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - NODE_ENV=development
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - builder

  builder:
    image: sf2lv2-builder:latest
    build: 
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./sf2lv2:/build/sf2lv2
      - ./backend/plugins/uploads:/input
      - ./backend/plugins/temp:/output
    environment:
      - CROSS_COMPILE=aarch64-linux-gnu-
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - AR=aarch64-linux-gnu-ar
      - LD=aarch64-linux-gnu-ld
      - STRIP=aarch64-linux-gnu-strip
      - BUILD_DIR=/build
    restart: unless-stopped 
