version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4001:4001"
    volumes:
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=4001
      - FRONTEND_URL=https://your-domain.com  # Replace with your domain
    restart: unless-stopped
    depends_on:
      - builder

  builder:
    build: ./docker
    volumes:
      - ./temp:/temp
    environment:
      - CROSS_COMPILE=aarch64-linux-gnu-
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - AR=aarch64-linux-gnu-ar
      - LD=aarch64-linux-gnu-ld
      - STRIP=aarch64-linux-gnu-strip
    restart: unless-stopped 