name: CICD Pipeline

on:
  push:
    branches: 
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Frontend with Docker Compose
        run: |
          cd frontend
          docker compose build --no-cache
          docker compose up -d
          docker ps -a

      - name: Cleanup unused Docker images
        run: docker image prune -f

  backend:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if backend files were modified
        id: backend_changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^backend/"; then
            echo "backend_changed=true" >> $GITHUB_ENV
          else
            echo "backend_changed=false" >> $GITHUB_ENV
          fi

      - name: Install Dependencies & Build Backend
        if: env.backend_changed == 'true'
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 22
          cd backend
          npm install
          npm run build

      - name: Start or Restart Backend with PM2
        if: env.backend_changed == 'true'
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 22
          cd backend
          if pm2 list | grep -q "sf2lv2-backend"; then
            echo "Restarting existing PM2 process..."
            pm2 restart sf2lv2-backend
          else
            echo "Starting PM2 process..."
            pm2 start dist/index.js --name sf2lv2-backend
          fi
          pm2 save

      - name: Setup PM2 Startup Script (Auto-run on reboot)
        if: env.backend_changed == 'true'
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 22
          sudo su -c "$(pm2 startup | tail -n 1)"
          pm2 save

      - name: PM2 Status
        if: env.backend_changed == 'true'
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 22
          pm2 status
