name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  
      - 'backend/**'   
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'  
      - 'backend/**'   
jobs:
  # Frontend Build and Run Job
  frontend:
    runs-on: self-hosted  
    if: github.event.head_commit.modified | contains('frontend') 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build Frontend with Docker Compose
        run: |
          cd frontend
          docker compose build
          docker compose up -d  
          cd ..
      - name: Cleanup unused Docker images
        run: |
          docker image prune -f 
        
  # Backend Build and Run Job
  backend:
    runs-on: self-hosted  # Use the self-hosted runner
    if: github.event.head_commit.modified | contains('backend')  # Only run if backend files are modified
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Backend Dependencies and Build
        run: |
          cd backend
          npm install
          npm run build
          cd ..
        
      - name: Restart Backend Service using systemd
        run: |
          sudo systemctl restart backend.service
          sudo systemctl status backend.service
