name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: islainstruments/sf2lv2web
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Move repository to correct directory
        run: |
          mv $GITHUB_WORKSPACE /home/ubuntu/sf2lv2web/sf2lv2web
          cd /home/ubuntu/sf2lv2web/sf2lv2web  # Change directory to where the repo is moved

      - name: Pull latest changes
        run: |
          git pull origin main  # Ensure we have the latest changes from the remote repository

      - name: Debug current directory
        run: |
          echo "Current Directory: $(pwd)"
          ls -l

      - name: Build Frontend with Docker Compose
        run: |
          cd /home/ubuntu/sf2lv2web/sf2lv2web/frontend  # Absolute path to frontend
          docker-compose build
          docker-compose up -d
          cd /home/ubuntu/sf2lv2web/sf2lv2web  # Go back to root directory

      - name: Cleanup unused Docker images
        run: |
          sudo docker image prune -f

  backend:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: islainstruments/sf2lv2web
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Move repository to correct directory
        run: |
          mv $GITHUB_WORKSPACE /home/ubuntu/sf2lv2web/sf2lv2web
          cd /home/ubuntu/sf2lv2web/sf2lv2web 

      - name: Pull latest changes
        run: |
          git pull origin main  

      - name: Check if backend files were modified
        id: backend_changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^backend/"; then
            echo "backend_changed=true" >> $GITHUB_ENV
          else
            echo "backend_changed=false" >> $GITHUB_ENV
          fi

      - name: Install Backend Dependencies and Build
        if: env.backend_changed == 'true'
        run: |
          cd /home/ubuntu/sf2lv2web/sf2lv2web/backend 
          npm install
          npm run build
          cd /home/ubuntu/sf2lv2web/sf2lv2web 

      - name: Restart Backend Service using systemd
        if: env.backend_changed == 'true'
        run: |
          sudo systemctl restart backend.service
          sudo systemctl status backend.service
