name: CICD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: islainstruments/sf2lv2web
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Debug current directory
        run: |
          echo "Workspace Directory: $GITHUB_WORKSPACE"
          ls -l $GITHUB_WORKSPACE

      - name: Build Frontend with Docker Compose
        run: |
          cd $GITHUB_WORKSPACE/frontend  # Using $GITHUB_WORKSPACE as the working directory
          docker compose build
          docker compose up -d
          docker ps -a
          cd $GITHUB_WORKSPACE  # Return to the workspace root

      - name: Cleanup unused Docker images
        run: |
          sudo docker image prune -f

  backend:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: islainstruments/sf2lv2web
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Debug current directory
        run: |
          echo "Workspace Directory: $GITHUB_WORKSPACE"
          ls -l $GITHUB_WORKSPACE

      - name: Check if backend files were modified
        id: backend_changed
        run: |
          # Check for any changes in the 'backend' directory
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^backend/"; then
            echo "backend_changed=true" >> $GITHUB_ENV
          else
            echo "backend_changed=false" >> $GITHUB_ENV
          fi

      - name: Install Backend Dependencies and Build
        if: env.backend_changed == 'true'
        run: |
          cd $GITHUB_WORKSPACE/backend  # Use the workspace path for backend
          npm install
          npm run build
          cd $GITHUB_WORKSPACE  # Return to the workspace root

      - name: Restart Backend Service with PM2
        if: env.backend_changed == 'true'
        run: |
          cd $GITHUB_WORKSPACE/backend  # Go to the backend directory
          pm2 restart sf2lv2-backend  # Restart the app with PM2

      - name: Check PM2 Status
        if: env.backend_changed == 'true'
        run: |
          pm2 status  # Check the status of the backend service
